# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/$VENDOR/$DEVICE/setup-makefiles.sh

if [[ $DEVICE == "" ]]; then
  echo "\$DEVICE appears to be null"
  echo "Are you running this from within your device variant's repo?"
  echo "Aborting..."
  exit 1
fi

OUTDIR=vendor/$VENDOR/$DEVICE
MAKEFILE=../../../$OUTDIR/$DEVICE-vendor-blobs.mk
(cat << EOF) > $MAKEFILE

PRODUCT_COPY_FILES += \\
EOF

if [ -f ../$DEVICE_COMMON/device-proprietary-files.txt ]; then
  LINEEND=" \\"
  COUNT=`wc -l device-proprietary-files.txt | awk {'print $1'}`
  DISM=`egrep -c '(^#|^$)' device-proprietary-files.txt`
  COUNT=`expr $COUNT - $DISM`
  for FILE in `egrep -v '(^#|^$)' ../$DEVICE_COMMON/device-proprietary-files.txt`; do
    COUNT=`expr $COUNT - 1`
    echo "        $OUTDIR/proprietary/$FILE:/system/$FILE$LINEEND" >> $MAKEFILE
  done
fi


OUTDIR=vendor/$VENDOR/$VENDOR_COMMON
MAKEFILE=../../../$OUTDIR/$VENDOR_COMMON-vendor-blobs.mk
(cat << EOF) > $MAKEFILE

LINEEND=" \\"
COUNT=`wc -l ../$DEVICE_COMMON/common-proprietary-files.txt | awk {'print $1'}`
DISM=`egrep -c '(^#|^$)' ../$DEVICE_COMMON/common-proprietary-files.txt`
COUNT=`expr $COUNT - $DISM`
for FILE in `egrep -v '(^#|^$)' ../$DEVICE_COMMON/common-proprietary-files.txt`; do
  COUNT=`expr $COUNT - 1`
  if [ $COUNT = "0" ]; then
    LINEEND=""
  fi
  echo "        $OUTDIR/proprietary/$FILE:/system/$FILE$LINEEND" >> $MAKEFILE
done
